#!/usr/bin/env python3
"""Emit a firmware header with the per-channel series R-L-C impedance model
(tools/fit_rlc_model.py -> rlc_fit.json), used by src/FreqGainModel.h to
correct the feedforward's assumed duty->current gain for the actual drive
frequency -- see progress.md Section 5 for the full derivation.

The state-space model's Bd/FF are built from a STATIC (DC, omega=0) gain
(tools/build_state_space_model.py), which is only exactly correct at each
channel's LC resonance f0 (where |Z(f0)|=R, the impedance minimum for a
series R-L-C). Away from f0 in either direction |Z(f)|>R strictly, so the
true required duty is u_ff_static * (|Z(f)|/R) -- always >= the static
estimate, never less (see the sign derivation in progress.md 5.5 -- an
earlier draft of this fix had the ratio inverted).

R/L/C are physical per-channel coil properties, independent of rotation
direction -- ONE shared header for both CW/CCW (unlike feedforward_cw.h/
_ccw.h, which do depend on direction via the coupling-fit's R matrix).

Usage:
  uv run python tools/build_freq_gain_header.py \
      --rlc-fit tools/rlc_fit.json --header ../src/rlc_gain_model.h
"""
from __future__ import annotations

import argparse
import json
import os


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--rlc-fit", default=os.path.join(os.path.dirname(__file__), "rlc_fit.json"))
    ap.add_argument("--channels", nargs="+", default=list("ABCD"), choices=list("ABCD"))
    ap.add_argument("--header", required=True)
    args = ap.parse_args()

    if not os.path.exists(args.rlc_fit):
        raise SystemExit(f"{args.rlc_fit} not found -- run tools/fit_rlc_model.py first")

    with open(args.rlc_fit) as f:
        rlc = json.load(f)
    missing = [ch for ch in args.channels if ch not in rlc]
    if missing:
        raise SystemExit(f"{args.rlc_fit} is missing channel(s) {missing}")

    for ch in args.channels:
        resid = rlc[ch]["resid_rms_a"]
        print(f"{ch}: R={rlc[ch]['R']:.6f} L={rlc[ch]['L']:.8f} C={rlc[ch]['C']:.8f} "
              f"f0={rlc[ch]['f0_hz']:.2f}Hz resid_rms={resid:.4f}A")

    def vals(key, prec):
        return ", ".join("{:.{}f}f".format(rlc[ch][key], prec) for ch in args.channels)

    lines = [
        "// GENERATED by tools/build_freq_gain_header.py -- do not hand-edit.",
        "// Per-channel series R-L-C impedance model (tools/fit_rlc_model.py),",
        "// fit directly against measured current across the 1-210Hz sweep.",
        "// Used by src/FreqGainModel.h to correct the feedforward's static",
        "// (DC, omega=0) gain assumption for the actual drive frequency --",
        "// see progress.md Section 5 for the full derivation. NOT direction-",
        "// dependent -- R/L/C are physical coil properties, shared CW/CCW.",
        "#pragma once",
        "",
        "const float RLC_R[NUM_CHANNELS] = {" + vals("R", 6) + "};",
        "const float RLC_L[NUM_CHANNELS] = {" + vals("L", 8) + "};",
        "const float RLC_C[NUM_CHANNELS] = {" + vals("C", 8) + "};",
        "",
    ]
    with open(args.header, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {args.header}")


if __name__ == "__main__":
    main()
