#!/usr/bin/env python3
"""Assemble the coupled 4-channel state-space plant model from the fitted
per-channel RLC model (tools/fit_rlc_model.py -> rlc_fit.json) and the fitted
mutual-inductance matrix (tools/fit_mutual_inductance.py -> m_matrix.json).

Physical model (see the state-space plan for the full derivation): each coil
is an R-L branch, magnetically coupled via mutual inductance M_ij. In matrix
form, with x = [i_A,i_B,i_C,i_D] (measured coil current) and u = [d_A..d_D]
(carrier duty %, 0-100):

  L*(dx/dt) + R*x = V(u)          V(u) = diag(Kv_i)*u,  Kv_i = (4/pi)*V_supply/100
  dx/dt = A x + B u
  A = -L^-1 R      (coupling enters through L^-1 even though R is diagonal)
  B =  L^-1 diag(Kv)

L is symmetric 4x4: diagonal = each channel's fitted self-inductance, off-
diagonal = the fitted M_ij pair (missing pairs default to 0 -- a genuine gap,
not a measured zero -- and are reported loudly).

The series capacitor C (fit_rlc_model.py fits R-L-C, not R-L) is deliberately
NOT included as a third dynamic state here, matching the precedent already set
by tools/compute_model_gains.py's IMC design (tau_elec = 2L/R): this is a
first-order-per-channel envelope model, not a full 2nd-order electrical model.
This is a known simplification -- validate it against real step-response data
with tools/validate_state_space_model.py before trusting it on hardware.

The discretization below (Ad = expm(A*Ts), Bd = A^-1(Ad-I)B) discretizes the
4-state RLC+M model directly. It does NOT separately model the current-sense
50ms EMA filter (CurrentSense.h) as an extra state -- Ts should be chosen
>= tau_filter_ms as a conservative approximation (the filter's own lag is
treated as already "inside" the achievable control period, not as a distinct
pole to observe around). See the plan's caveats section.

Usage:
  uv run python tools/build_state_space_model.py \
      --rlc-fit tools/rlc_fit.json --m-matrix tools/m_matrix.json \
      --v-supply 11.9 --ts 0.05 --out tools/state_space_model.json \
      --header ../src/plant_model.h
"""
from __future__ import annotations

import argparse
import itertools
import json
import os

import numpy as np
from scipy.linalg import expm


def build_L(rlc: dict, m_matrix: dict, channels: list[str]) -> tuple[np.ndarray, list[str]]:
    n = len(channels)
    L = np.zeros((n, n))
    for i, ch in enumerate(channels):
        L[i, i] = rlc[ch]["L"]
    missing_pairs = []
    for i, j in itertools.combinations(range(n), 2):
        key = "".join(sorted([channels[i], channels[j]]))
        if key in m_matrix:
            L[i, j] = L[j, i] = m_matrix[key]
        else:
            missing_pairs.append(key)
    return L, missing_pairs


def build_state_space(rlc: dict, m_matrix: dict, v_supply: float,
                       channels: list[str]) -> dict:
    n = len(channels)
    L, missing_pairs = build_L(rlc, m_matrix, channels)
    R = np.diag([rlc[ch]["R"] for ch in channels])
    Kv = np.array([(4.0 / np.pi) * v_supply / 100.0 for _ in channels])  # A/duty% -> V, same for all channels (duty-normalized)

    L_inv = np.linalg.inv(L)
    A = -L_inv @ R
    B = L_inv @ np.diag(Kv)

    return {"A": A, "B": B, "L": L, "R": R, "Kv": Kv, "missing_pairs": missing_pairs}


def discretize(A: np.ndarray, B: np.ndarray, Ts: float) -> tuple[np.ndarray, np.ndarray]:
    Ad = expm(A * Ts)
    Bd = np.linalg.solve(A, (Ad - np.eye(A.shape[0])) @ B)
    return Ad, Bd


def write_header(path: str, channels: list[str], rlc: dict, Kv: np.ndarray) -> None:
    r_vals = ", ".join("{:.6f}f".format(rlc[ch]["R"]) for ch in channels)
    l_vals = ", ".join("{:.8f}f".format(rlc[ch]["L"]) for ch in channels)
    kv_vals = ", ".join("{:.6f}f".format(k) for k in Kv)
    lines = [
        "// GENERATED by tools/build_state_space_model.py -- do not hand-edit.",
        "// Per-channel plant constants for the LQR feedforward term",
        "// (u_ff_i = R_i * r / Kv_i, the steady-state duty->current relation).",
        "#pragma once",
        "",
        "const float PLANT_R_OHM[NUM_CHANNELS] = {" + r_vals + "};",
        "const float PLANT_L_H[NUM_CHANNELS]   = {" + l_vals + "};",
        "const float PLANT_KV[NUM_CHANNELS]    = {" + kv_vals + "};",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--rlc-fit", default=os.path.join(os.path.dirname(__file__), "rlc_fit.json"))
    ap.add_argument("--m-matrix", default=os.path.join(os.path.dirname(__file__), "m_matrix.json"),
                     help="missing pairs default to 0 coupling and are reported, not fatal")
    ap.add_argument("--v-supply", type=float, required=True,
                     help="bench supply voltage to assume for the Kv (duty->voltage) term")
    ap.add_argument("--channels", nargs="+", default=list("ABCD"), choices=list("ABCD"))
    ap.add_argument("--ts", type=float, default=0.05,
                     help="discretization sample time, seconds -- keep >= the current-sense "
                          "filter's tau (50ms default in CurrentSense.h) (default: %(default)s)")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "state_space_model.json"))
    ap.add_argument("--header", default=os.path.join(os.path.dirname(__file__), "..", "src", "plant_model.h"))
    args = ap.parse_args()

    if not os.path.exists(args.rlc_fit):
        raise SystemExit(f"{args.rlc_fit} not found -- run tools/fit_rlc_model.py first "
                          "(see the state-space plan's Phase A)")

    with open(args.rlc_fit) as f:
        rlc = json.load(f)
    missing_rlc = [ch for ch in args.channels if ch not in rlc]
    if missing_rlc:
        raise SystemExit(f"rlc_fit.json is missing channel(s) {missing_rlc}")

    m_matrix = {}
    if os.path.exists(args.m_matrix):
        with open(args.m_matrix) as f:
            m_matrix = json.load(f)
    else:
        print(f"WARNING: {args.m_matrix} not found -- treating ALL mutual inductance "
              "as 0 (uncoupled model). Run tools/fit_mutual_inductance.py for the real "
              "coupling before trusting this for LQR design.")

    model = build_state_space(rlc, m_matrix, args.v_supply, args.channels)
    if model["missing_pairs"]:
        print(f"WARNING: m_matrix.json is missing pair(s) {model['missing_pairs']} -- "
              "those couplings are set to 0, not measured-and-confirmed-zero.")

    Ad, Bd = discretize(model["A"], model["B"], args.ts)
    eig_A = np.linalg.eigvals(model["A"])
    print(f"continuous A eigenvalues (should be real, negative -- stable RL decay): {eig_A}")
    print(f"L matrix (H):\n{model['L']}")

    out = {
        "channels": args.channels,
        "v_supply": args.v_supply,
        "ts": args.ts,
        "A": model["A"].tolist(),
        "B": model["B"].tolist(),
        "Ad": Ad.tolist(),
        "Bd": Bd.tolist(),
        "L": model["L"].tolist(),
        "R": model["R"].tolist(),
        "Kv": model["Kv"].tolist(),
        "missing_coupling_pairs": model["missing_pairs"],
    }
    with open(args.out, "w") as f:
        json.dump(out, f, indent=2)
    print(f"wrote {args.out}")

    write_header(args.header, args.channels, rlc, model["Kv"])
    print(f"wrote {args.header}")


if __name__ == "__main__":
    main()
