#!/usr/bin/env python3
"""Compute the full coupling-aware feedforward matrix FF = Bd^-1 from the
fitted discrete plant model (tools/build_state_space_model.py ->
state_space_model.json), replacing the old per-channel-only feedforward
(u_ff_i = R_i*r/Kv_i in main_state_space.cpp), which ignores coupling
entirely and left the integral term to slowly "discover" cross-channel
correction over many ticks -- observed on hardware as ~10-20s RAMP_UP
convergence time before HOLD-phase spread settles.

Since this plant is near-memoryless at Ts (Bd numerically matches the
independently-measured static DC gain matrix, see
tools/fit_coupling_matrix.py -- Ad~0), x_{k+1} ~= Bd @ u_k essentially
exactly. So u = Bd^-1 @ x_target is the EXACT feedforward duty command to
hit x_target in one tick, given the fitted model is accurate -- not an
approximation or a "linearization" in the usual sense, since there's no
higher-order dynamics being linearized away. Feedback (K_x/K_d/K_z) then
only has to correct residual model error (thermal drift, fit imprecision,
duty saturation), not rediscover the coupling structure from scratch.

Usage:
  uv run python tools/build_feedforward.py --model tools/state_space_model.json \
      --header ../src/feedforward_cw.h --name-suffix _CW
"""
from __future__ import annotations

import argparse
import json
import os

import numpy as np


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", required=True)
    ap.add_argument("--header", required=True)
    ap.add_argument("--name-suffix", default="")
    ap.add_argument("--max-cond", type=float, default=1e4,
                     help="refuse to invert Bd if its condition number exceeds this "
                          "(default: %(default)s)")
    args = ap.parse_args()

    if not os.path.exists(args.model):
        raise SystemExit(f"{args.model} not found -- run tools/build_state_space_model.py first")

    with open(args.model) as f:
        model = json.load(f)
    Bd = np.array(model["Bd"])

    cond = np.linalg.cond(Bd)
    print(f"Bd condition number: {cond:.3f}")
    if cond > args.max_cond:
        raise SystemExit(f"Bd is too ill-conditioned to invert reliably "
                          f"(cond={cond:.2e} > --max-cond={args.max_cond:.2e})")

    FF = np.linalg.inv(Bd)
    resid = float(np.max(np.abs(FF @ Bd - np.eye(Bd.shape[0]))))
    print(f"max |FF@Bd - I| = {resid:.2e} (should be ~machine precision)")
    print(f"FF = Bd^-1 =\n{FF}")

    def mat_lines(name, M):
        n = M.shape[0]
        rows = []
        for i in range(n):
            row_vals = ", ".join("{:.8f}f".format(v) for v in M[i])
            rows.append("  {" + row_vals + "}")
        return [f"const float {name}[NUM_CHANNELS][NUM_CHANNELS] = {{",
                ",\n".join(rows), "};", ""]

    lines = [
        "// GENERATED by tools/build_feedforward.py -- do not hand-edit.",
        "// Full coupling-aware feedforward: FF = Bd^-1 (see this script's",
        "// docstring). u_ff = FF @ x_target -- the exact (given the fitted",
        "// model) duty command to hit x_target in one control tick on this",
        "// near-memoryless plant. Replaces the old per-channel-only",
        "// u_ff_i = R_i*r/Kv_i, which ignored coupling entirely.",
        "// BD is the fitted discrete input matrix itself (not inverted) --",
        "// needed directly by DutyAllocator's constrained optimization.",
        "#pragma once",
        "",
    ]
    lines += mat_lines(f"FEEDFORWARD{args.name_suffix}", FF)
    lines += mat_lines(f"BD{args.name_suffix}", Bd)
    with open(args.header, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {args.header}")


if __name__ == "__main__":
    main()
