#!/usr/bin/env python3
"""Design a discrete-time LQR state-feedback gain matrix K from the coupled
4-channel plant model (tools/build_state_space_model.py -> state_space_model.json).

Control law (see the state-space plan): u = u_ff(r) - K(x - x_ref), x_ref =
r*[1,1,1,1] (a shared target current across all 4 channels). This script only
designs K, the feedback term; u_ff(r) is computed in firmware from
plant_model.h's per-channel R_i/Kv_i (steady-state duty->current relation).

Cost function: J = sum_k x_k^T Q x_k + u_k^T R u_k. Q is built from two
weights so "penalize spread between channels" is an explicit, separate knob
from "track the shared target":

  Q = q_track * I + q_spread * (n*I - ones(n,n))

The second term is the (scaled) graph Laplacian of the complete graph on the
4 channels: x^T(n*I - J)x = sum_{i<j} (x_i - x_j)^2 -- it penalizes pairwise
differences ONLY (its null space is the uniform vector [1,1,1,1], i.e. all
channels equal at any shared magnitude costs nothing from this term), which
is exactly the "equalize the 4 channels" objective from a per-channel PID
cannot express as a cost function (PID's cost, if it had one, would be
separable per loop -- this term is not separable).

R = r_duty * I penalizes actuation effort (duty deviation from feedforward).

Usage:
  uv run python tools/design_lqr_gains.py --model tools/state_space_model.json \
      --q-track 1.0 --q-spread 50.0 --r-duty 0.1 \
      --out tools/lqr_gains.json --header ../src/lqr_gains.h
"""
from __future__ import annotations

import argparse
import json
import os

import numpy as np
from scipy.linalg import solve_discrete_are


def build_Q(n: int, q_track: float, q_spread: float) -> np.ndarray:
    return q_track * np.eye(n) + q_spread * (n * np.eye(n) - np.ones((n, n)))


def design_lqr(Ad: np.ndarray, Bd: np.ndarray, Q: np.ndarray, R: np.ndarray) -> np.ndarray:
    P = solve_discrete_are(Ad, Bd, Q, R)
    K = np.linalg.solve(R + Bd.T @ P @ Bd, Bd.T @ P @ Ad)
    return K


def write_header(path: str, K: np.ndarray) -> None:
    n = K.shape[0]
    rows = []
    for i in range(n):
        row_vals = ", ".join("{:.8f}f".format(v) for v in K[i])
        rows.append("  {" + row_vals + "}")
    lines = [
        "// GENERATED by tools/design_lqr_gains.py -- do not hand-edit.",
        "// LQR state-feedback gain: u = u_ff(r) - LQR_K @ (x - x_ref).",
        "#pragma once",
        "",
        "const float LQR_K[NUM_CHANNELS][NUM_CHANNELS] = {",
        ",\n".join(rows),
        "};",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", default=os.path.join(os.path.dirname(__file__), "state_space_model.json"))
    ap.add_argument("--q-track", type=float, default=1.0,
                     help="cost weight on tracking the shared target r (default: %(default)s)")
    ap.add_argument("--q-spread", type=float, default=50.0,
                     help="cost weight on pairwise spread between channels -- the main "
                          "'equalize' knob; raise this relative to q-track to prioritize "
                          "spread over tracking speed (default: %(default)s)")
    ap.add_argument("--r-duty", type=float, default=0.1,
                     help="cost weight on duty actuation effort (default: %(default)s)")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "lqr_gains.json"))
    ap.add_argument("--header", default=os.path.join(os.path.dirname(__file__), "..", "src", "lqr_gains.h"))
    args = ap.parse_args()

    if not os.path.exists(args.model):
        raise SystemExit(f"{args.model} not found -- run tools/build_state_space_model.py first")

    with open(args.model) as f:
        model = json.load(f)
    Ad = np.array(model["Ad"])
    Bd = np.array(model["Bd"])
    n = Ad.shape[0]

    Q = build_Q(n, args.q_track, args.q_spread)
    R = args.r_duty * np.eye(n)
    K = design_lqr(Ad, Bd, Q, R)

    eig_cl = np.linalg.eigvals(Ad - Bd @ K)
    max_mag = np.max(np.abs(eig_cl))
    print(f"closed-loop eigenvalues (discrete, must be inside unit circle): {eig_cl}")
    print(f"max |eigenvalue| = {max_mag:.4f}  -> {'STABLE' if max_mag < 1.0 else 'UNSTABLE -- do not flash this K'}")
    print(f"K =\n{K}")

    if max_mag >= 1.0:
        raise SystemExit("designed K is not stabilizing for this model -- refusing to write "
                          "output. Check the model (tools/state_space_model.json) or loosen "
                          "--r-duty / adjust --ts in build_state_space_model.py before retrying.")

    out = {
        "K": K.tolist(),
        "q_track": args.q_track,
        "q_spread": args.q_spread,
        "r_duty": args.r_duty,
        "closed_loop_eig": [[float(v.real), float(v.imag)] for v in eig_cl],
        "channels": model["channels"],
    }
    with open(args.out, "w") as f:
        json.dump(out, f, indent=2)
    print(f"wrote {args.out}")

    write_header(args.header, K)
    print(f"wrote {args.header}")


if __name__ == "__main__":
    main()
