// GENERATED by tools/design_lqr_gains.py -- do not hand-edit.
// Integral- (and optionally derivative-) augmented LQR (see this
// script's docstring -- the fitted plant is near-memoryless at this
// control rate, so plain state feedback K_x is expected to be weak;
// K_z (integral-of-error feedback) is where most of the real
// closed-loop correction comes from. K_d (derivative-of-error
// feedback) is ~0 unless --q-derivative was nonzero when this was
// generated.
// u = u_ff(r) - LQR_KX @ (x - x_ref) - LQR_KD @ derr_filt - LQR_KZ @ z_integral
// z_integral[k+1] = z_integral[k] + Ts * (x_ref - x[k])  (anti-windup: freeze on saturation)
// derr_filt = low-pass-filtered (err - err_prev) / Ts  (see main_state_space.cpp)
#pragma once

const float LQR_KX_CCW[NUM_CHANNELS][NUM_CHANNELS] = {
  {2.09614962f, -0.29288284f, -1.46997815f, -0.04366143f},
  {-0.30292074f, 2.15256062f, -1.55131811f, -0.01481305f},
  {-0.53474999f, -0.51949874f, 1.96688193f, -0.26155075f},
  {-0.47723234f, -0.60296874f, -0.60377063f, 1.81648114f}
};

const float LQR_KD_CCW[NUM_CHANNELS][NUM_CHANNELS] = {
  {-0.00000000f, -0.00000000f, -0.00000000f, -0.00000000f},
  {-0.00000000f, -0.00000000f, -0.00000000f, -0.00000000f},
  {-0.00000000f, -0.00000000f, -0.00000000f, -0.00000000f},
  {-0.00000000f, -0.00000000f, -0.00000000f, -0.00000000f}
};

const float LQR_KZ_CCW[NUM_CHANNELS][NUM_CHANNELS] = {
  {41.92299231f, -5.85765681f, -29.39956309f, -0.87322868f},
  {-6.05841487f, 43.05121231f, -31.02636214f, -0.29626097f},
  {-10.69499971f, -10.38997477f, 39.33763851f, -5.23101506f},
  {-9.54464678f, -12.05937475f, -12.07541266f, 36.32962271f}
};
