// GENERATED by tools/design_lqr_gains.py -- do not hand-edit.
// Integral- (and optionally derivative-) augmented LQR (see this
// script's docstring -- the fitted plant is near-memoryless at this
// control rate, so plain state feedback K_x is expected to be weak;
// K_z (integral-of-error feedback) is where most of the real
// closed-loop correction comes from. K_d (derivative-of-error
// feedback) is ~0 unless --q-derivative was nonzero when this was
// generated.
// u = u_ff(r) - LQR_KX @ (x - x_ref) - LQR_KD @ derr_filt - LQR_KZ @ z_integral
// z_integral[k+1] = z_integral[k] + Ts * (x_ref - x[k])  (anti-windup: freeze on saturation)
// derr_filt = low-pass-filtered (err - err_prev) / Ts  (see main_state_space.cpp)
#pragma once

const float LQR_KX_CW[NUM_CHANNELS][NUM_CHANNELS] = {
  {1.51684133f, -0.27694825f, -0.04316690f, -1.02827951f},
  {-0.31609724f, 1.49907410f, 0.00834189f, -1.03970364f},
  {-0.42079304f, -0.47185271f, 1.43098535f, -0.46522467f},
  {-0.31419900f, -0.24794727f, -0.16868427f, 1.13300901f}
};

const float LQR_KD_CW[NUM_CHANNELS][NUM_CHANNELS] = {
  {-0.00000000f, -0.00000000f, -0.00000000f, -0.00000000f},
  {-0.00000000f, -0.00000000f, -0.00000000f, -0.00000000f},
  {-0.00000000f, -0.00000000f, -0.00000000f, -0.00000000f},
  {-0.00000000f, -0.00000000f, -0.00000000f, -0.00000000f}
};

const float LQR_KZ_CW[NUM_CHANNELS][NUM_CHANNELS] = {
  {30.33682653f, -5.53896502f, -0.86333790f, -20.56559029f},
  {-6.32194479f, 29.98148193f, 0.16683784f, -20.79407277f},
  {-8.41586082f, -9.43705415f, 28.61970707f, -9.30449341f},
  {-6.28398000f, -4.95894549f, -3.37368533f, 22.66018010f}
};
