// PLACEHOLDER -- generated by tools/design_lqr_gains.py, but no real plant
// model exists yet (see src/plant_model.h and the state-space plan, Phase A).
// All-zero K disables feedback correction entirely: the controller falls back
// to pure feedforward (u = u_ff(r), same value applied to every channel since
// plant_model.h's placeholder constants are identical across channels) --
// deliberately safe (equivalent to the old START_DUTY behavior) rather than
// applying an unvalidated coupling correction.
//
// Regenerate for real once tools/state_space_model.json exists:
//   uv run python tools/design_lqr_gains.py --model tools/state_space_model.json
#pragma once

const float LQR_K[NUM_CHANNELS][NUM_CHANNELS] = {
  {0.0f, 0.0f, 0.0f, 0.0f},
  {0.0f, 0.0f, 0.0f, 0.0f},
  {0.0f, 0.0f, 0.0f, 0.0f},
  {0.0f, 0.0f, 0.0f, 0.0f}
};
