// Swim: ramp 1->30Hz over 20s, then undulate 30<->22Hz five times at 100%
// carrier, PI-balanced. Runs on boot -- no arming. Schedule (with its own
// direction=CCW) lives in /swim.json, generated by ai/gen_swim_experiment.py.
#include "drive_common.h"

static PwmController ctl(PWM_PINS, PHASES_CCW, INITIAL_DUTY, NUM_CHANNELS);
static JsonPhaseSequencer seq(&ctl);

void setup() {
  driveBoot();
  ctl.begin(); // DC (stationary); the schedule sets the running frequency
  ctl.initCarrierPWM(CARRIER_PINS, PWM_FREQ, CARRIER_ZERO);
  ctl.enableCurrentSense(ADC_PINS, SENS);
  ctl.enableCurrentBalance();
  seq.loadFromJsonFile("/swim.json");
  seq.start();
}

void loop() {
  seq.run();
  ctl.run();
  driveTelemetry(ctl); // also polls the block/restart button
}
