// Coil-coupling characterization sweep (solo + pairwise + all-4, several current
// levels), CW. Passthrough (piEnabled=false): it deliberately drives channels
// unequally to measure mutual coupling, so the balance loop must NOT equalize
// them. Loads /coupling_cw.json (swap to /coupling_ccw.json for the other
// direction). Generated by tools/gen_coupling_experiment.py -- do not hand-edit.
#include "balanced_experiment.h"

void setup() {
  // jsonFile, ccwDefault, driveFreq, iSafetyMax, piEnabled
  experimentSetup(ExperimentConfig("/coupling_cw.json", false, 190.0f, 10.0f, false));
}

void loop() { experimentLoop(); }
