// Coil-coupling characterization sweep (solo + pairwise + all-4, several current
// levels), CW. PASSTHROUGH (no enableCurrentBalance): it deliberately drives
// channels unequally to measure mutual coupling, so the balance loop must NOT
// equalize them. Runs on boot -- no arming. Loads /coupling_cw.json (swap to
// /coupling_ccw.json for the other direction). Generated by
// ai/gen_coupling_experiment.py -- do not hand-edit the JSON.
#include "drive_common.h"

static PwmController ctl(PWM_PINS, PHASES_CW, INITIAL_DUTY, NUM_CHANNELS);
static JsonPhaseSequencer seq(&ctl);

void setup() {
  driveBoot();
  ctl.begin(); // DC (stationary); the schedule sets the running frequency
  ctl.initCarrierPWM(CARRIER_PINS, PWM_FREQ, CARRIER_ZERO);
  ctl.enableCurrentSense(ADC_PINS, SENS, /*tripA*/ 10.0f); // no balance: passthrough
  seq.loadFromJsonFile("/coupling_cw.json");
  seq.start();
}

void loop() {
  seq.run();
  ctl.run();

  // --- experiment-specific behavior: blink the LED once per schedule step ---
  static size_t lastStep = (size_t)-1;
  size_t step = seq.currentIndex();
  if (step != lastStep) {
    lastStep = step;
    digitalWrite(LED_PIN, !digitalRead(LED_PIN));
  }

  driveTelemetry(ctl);
}
