// PLACEHOLDER -- generated by tools/build_state_space_model.py, but no real
// system-ID data exists yet (see the state-space plan, Phase A: the solo-
// sweep + mutual-inductance captures have not been run on hardware). These
// values are generic guesses (R ~ 1 ohm, L ~ 20mH, Kv from a nominal 12V
// supply), NOT fitted to this hardware. They only need to be plausible
// enough that the feedforward term (u_ff_i = R_i * r / Kv_i) produces a
// sane starting duty -- DUTY_MIN/DUTY_MAX and I_MAX_A in main_state_space.cpp
// are what actually keep this safe, not the accuracy of these constants.
//
// Regenerate for real once Phase A is done:
//   uv run python tools/build_state_space_model.py --rlc-fit tools/rlc_fit.json \
//       --m-matrix tools/m_matrix.json --v-supply <measured> --out tools/state_space_model.json
#pragma once

const float PLANT_R_OHM[NUM_CHANNELS] = {1.0f, 1.0f, 1.0f, 1.0f};
const float PLANT_L_H[NUM_CHANNELS]   = {0.02f, 0.02f, 0.02f, 0.02f};
const float PLANT_KV[NUM_CHANNELS]    = {0.15279f, 0.15279f, 0.15279f, 0.15279f};  // (4/pi)*12V/100
