// GENERATED by tools/build_freq_gain_header.py -- do not hand-edit.
// Per-channel series R-L-C impedance model (tools/fit_rlc_model.py),
// fit directly against measured current across the 1-210Hz sweep.
// Used by src/FreqGainModel.h to correct the feedforward's static
// (DC, omega=0) gain assumption for the actual drive frequency --
// see progress.md Section 5 for the full derivation. NOT direction-
// dependent -- R/L/C are physical coil properties, shared CW/CCW.
#pragma once

const float RLC_R[NUM_CHANNELS] = {0.256009f, 0.224013f, 0.253631f, 0.278565f};
const float RLC_L[NUM_CHANNELS] = {0.00094577f, 0.00078906f, 0.00092349f, 0.00108515f};
const float RLC_C[NUM_CHANNELS] = {0.00112778f, 0.00132813f, 0.00116538f, 0.00099623f};
