function open_loop_two_ring()
% OPEN_LOOP_TWO_RING  Two antiphase rotating rings plus a steady ring, and the axial
% moment that makes the steady one do anything. Chapter 4 section 15.
%
%   Self-contained on purpose. The physics helpers inside
%   MultiCoilBeamformingGUI_quickGeom_rigidTilt_coil22mm.m are local to that file and
%   cannot be called from here, so the few pieces needed are reimplemented below with
%   the same names and the same point-dipole field, and checked against a fixture
%   generated by the Python model.
%
%   NOT RUN BY ITS AUTHOR. MATLAB is not available in the environment this was written
%   in, so this file has never been executed and is unverified. two_ring_fixture.csv exists precisely so that you
%   can verify it in one command: any disagreement past 1e-9 is a porting bug here, not
%   a physics difference. Python (controller/control/) is the source of truth.
%
%   Three results this file exists to carry across (section 15):
%
%     1. The transverse field on the array axis goes as (z - z_coil), so a coil plane
%        level with the robot drives nothing, and a second ring must be reverse-wound
%        or the two cancel.
%     2. A steady field exerts exactly zero cycle-averaged force and torque on a rotor
%        whose moment lies in the spin plane, because <m> = 0 over a cycle.
%     3. Give the rotor a moment along its spin axis and the steady field acts on that
%        alone, decoupled from the rotating drive. That is what separates the axial trap
%        from the drive field, which Earnshaw otherwise ties together.
%
%   Usage:  open_loop_two_ring

    fprintf('\n=== two-ring array plus a steady ring, chapter 4 section 15 ===\n\n');

    rob   = robotParams();
    coils = buildTwoRing();

    verifyAgainstFixture(coils, rob);
    showAxialOffsetResult(coils);
    showSteadyChannelResult(coils, rob);
end

% ---------------------------------------------------------------------------
% Geometry
% ---------------------------------------------------------------------------

function coils = buildTwoRing()
% The section 15.7 design. Lower ring at z = -11 mm, upper reverse-wound at +50.7 mm,
% steady ring level with the robot at 19.9 mm.

    r_lo = 0.0367;  z_lo = -0.0110;
    r_hi = 0.0367;  z_hi =  0.0507;
    pitch = 0.021;  amp = 0.9727;          % A, what a 12 V rail delivers at 110 Hz
    r_dc = 0.0601;  z_dc = 0.0199;  i_dc = 1.9955;
    coilR = 0.0105; turns = 650;

    phases = deg2rad([0, 270, 180, 90]);
    pos = []; nhat = []; amps = []; phase = []; dc = [];

    for ring = 1:2
        if ring == 1, rr = r_lo; zz = z_lo; extra = 0;
        else,         rr = r_hi; zz = z_hi; extra = pi;   % reverse-wound: this is the
        end                                               % whole trick, see result 1
        for g = 1:4
            ang = deg2rad(90*(g-1));
            er = [cos(ang), sin(ang), 0];
            et = [-er(2), er(1), 0];                      % pairs split tangentially, so
            for sgn = [-1, 1]                             % both stay on the ring
                pos   = [pos;  [rr*cos(ang), rr*sin(ang), zz] + 0.5*pitch*sgn*et]; %#ok<AGROW>
                nhat  = [nhat; 0 0 1];       %#ok<AGROW>
                amps  = [amps; amp];         %#ok<AGROW>
                phase = [phase; phases(g) + extra]; %#ok<AGROW>
                dc    = [dc; 0];             %#ok<AGROW>
            end
        end
    end

    % The steady ring sits level with the robot: a ring's on-axis Bz peaks in its own
    % plane, which is where an axial trap must be, and is exactly where result 1 says it
    % contributes no rotating field at all.
    for g = 1:4
        ang = deg2rad(90*(g-1));
        pos   = [pos;  r_dc*cos(ang), r_dc*sin(ang), z_dc]; %#ok<AGROW>
        nhat  = [nhat; 0 0 1];  %#ok<AGROW>
        amps  = [amps; 0];      %#ok<AGROW>   no rotating current in the steady ring
        phase = [phase; 0];     %#ok<AGROW>
        dc    = [dc; i_dc];     %#ok<AGROW>
    end

    coils.pos = pos;  coils.nhat = nhat;  coils.Iamp = amps;
    coils.phase = phase;  coils.Idc = dc;
    coils.R = repmat(coilR, size(pos,1), 1);
    coils.Nturn = repmat(turns, size(pos,1), 1);
end

function p = robotParams()
% CAD body plus two N52 magnets, matching spatial_model.robot_params, and the axial
% moment section 15.2 adds.

    mu0 = 4*pi*1e-7;
    m_body_g = 0.06;  m_mag_g = 11.7832e-3;  nMag = 2;
    r_mag = 0.79375e-3;  h_mag = 0.79375e-3;
    p.mass  = (m_body_g + nMag*m_mag_g) * 1e-3;
    p.Ispin = 3.3578361348541667e-9;                 % section 3
    Vmag = pi * r_mag^2 * h_mag;
    p.mdip = nMag * (1.45/mu0) * Vmag;
    p.m_axial = 0.03 * p.mdip;                      % 3 %, section 15.2
end

% ---------------------------------------------------------------------------
% Field. Same point-dipole stub as B_from_coil_stub in the GUI.
% ---------------------------------------------------------------------------

function B = B_from_coil_stub(r, cpos, nhat, R, N, I)
% Point dipole, as in the GUI, with one deliberate difference. The GUI writes
% d = norm(dr) + 1e-9, which biases *every* evaluation rather than only guarding the
% singularity: at a 40 mm working distance that is 7.5e-8 in relative field, and it is
% exactly why an otherwise identical port disagreed with Python at the 1e-7 level.
% max(norm(dr), 1e-9) guards without biasing.
    mu0 = 4*pi*1e-7;
    m  = I * N * pi * R^2 * nhat;
    dr = r - cpos;  d = max(norm(dr), 1e-9);
    B  = (mu0/(4*pi)) * ((3*dot(m,dr)*dr)/d^5 - m/d^3);
end

function [u, v] = harmonicUVAtPoint(r, coils)
% B(theta) = u cos(theta) + v sin(theta), summed over the rotating coils only.
    u = [0 0 0];  v = [0 0 0];
    for c = 1:size(coils.pos,1)
        if coils.Iamp(c) == 0, continue; end
        b1 = B_from_coil_stub(r, coils.pos(c,:), coils.nhat(c,:), ...
                              coils.R(c), coils.Nturn(c), 1.0);
        u = u + b1 * ( coils.Iamp(c) * cos(coils.phase(c)));
        v = v + b1 * (-coils.Iamp(c) * sin(coils.phase(c)));
    end
end

function B = dcFieldAtPoint(r, coils)
% Steady field from the DC currents. Kept separate from the harmonics because the two
% act on different parts of the robot and never mix (section 15.2).
    B = [0 0 0];
    for c = 1:size(coils.pos,1)
        if coils.Idc(c) == 0, continue; end
        B = B + B_from_coil_stub(r, coils.pos(c,:), coils.nhat(c,:), ...
                                 coils.R(c), coils.Nturn(c), coils.Idc(c));
    end
end

function [a, b] = ellipseSemiaxes(u, v)
    G = [dot(u,u), dot(u,v); dot(u,v), dot(v,v)];
    tr = trace(G);  dt = max(det(G), 0);
    disc = sqrt(max(tr*tr - 4*dt, 0));
    a = sqrt(max(0.5*(tr + disc), 0));
    b = sqrt(max(0.5*(tr - disc), 0));
end

% ---------------------------------------------------------------------------
% The three results
% ---------------------------------------------------------------------------

function verifyAgainstFixture(coils, rob) %#ok<INUSD>
    f = fullfile(fileparts(mfilename('fullpath')), 'two_ring_fixture.csv');
    if ~isfile(f)
        fprintf('fixture  : two_ring_fixture.csv not found, skipping verification\n\n');
        return
    end
    T = readtable(f);
    worst = 0;
    for k = 1:height(T)
        if T.z(k) < 0, r = [0.003, 0.001, 0.020];   % the off-axis row
        else,          r = [0, 0, T.z(k)];
        end
        [u, v] = harmonicUVAtPoint(r, coils);
        [a, b] = ellipseSemiaxes(u, v);
        Bdc = dcFieldAtPoint(r, coils);
        e = max([abs(u - [T.ux(k) T.uy(k) T.uz(k)]), ...
                 abs(v - [T.vx(k) T.vy(k) T.vz(k)]), ...
                 abs(a - T.a(k)), abs(b - T.b(k)), abs(Bdc(3) - T.bdc_z(k))]);
        worst = max(worst, e / max(a, 1e-12));
    end
    fprintf('fixture  : worst relative disagreement with Python %.2e over %d points\n', ...
            worst, height(T));
    % 1e-6, not machine precision. The fixture is exact against the Python model, but this
    % file has never been executed, so the threshold is set where a real porting bug (a wrong
    % phase, a transposed axis, a missing reversal) shows up as 1e-1 or worse while harmless
    % last-digit differences do not trip it.
    if worst > 1e-6
        warning(['port disagrees with the Python model by %.2e: that is a bug in this ' ...
                 'file, not new physics. controller/control/ is the source of truth.'], worst);
    else
        fprintf('           within tolerance, so the port carries the same physics\n');
    end
    fprintf('\n');
end

function showAxialOffsetResult(coils)
% Result 1: the transverse field goes as (z - z_coil), so it vanishes in a coil plane
% and reverses across it. This is why the upper ring is reverse-wound.
    % Lower ring alone: the property is about one ring, and with both present the upper
    % one contributes in the lower plane and the demonstration says nothing.
    lower = coils;
    keep = (coils.Iamp > 0) & (coils.pos(:,3) < 0);
    lower.pos = coils.pos(keep,:);   lower.nhat = coils.nhat(keep,:);
    lower.Iamp = coils.Iamp(keep);   lower.phase = coils.phase(keep);
    lower.Idc = coils.Idc(keep);     lower.R = coils.R(keep);
    lower.Nturn = coils.Nturn(keep);

    zc = lower.pos(1,3);
    [u0, ~] = harmonicUVAtPoint([0 0 zc], lower);
    [up, ~] = harmonicUVAtPoint([0 0 zc + 0.02], lower);
    [um, ~] = harmonicUVAtPoint([0 0 zc - 0.02], lower);
    fprintf('result 1 : |u| in the lower ring''s own plane   = %.3e T\n', norm(u0));
    fprintf('           |u| 20 mm above / below            = %.3e / %.3e T\n', ...
            norm(up), norm(um));
    fprintf('           the transverse field goes as (z - z_coil): zero in the plane,\n');
    fprintf('           reversing across it, which is why a second ring must be\n');
    fprintf('           reverse-wound or the two simply cancel.\n\n');
end

function showSteadyChannelResult(coils, rob)
% Results 2 and 3: a steady field is inert on an in-plane moment, and acts only on an
% axial one.
    r = [0 0 0.0199];
    Bdc = dcFieldAtPoint(r, coils);
    fprintf('result 2 : |B_dc| at the working point        = %.3f mT\n', norm(Bdc)*1e3);
    fprintf('           cycle-averaged force and torque on the in-plane moment: exactly\n');
    fprintf('           zero, because <m> = 0 over a cycle. Not small, zero.\n\n');

    h = 1e-5;
    Bp = dcFieldAtPoint(r + [0 0 h], coils);
    Bm = dcFieldAtPoint(r - [0 0 h], coils);
    dBz = (Bp(3) - Bm(3)) / (2*h);
    Fz  = rob.m_axial * dBz;
    fprintf('result 3 : with m_axial = %.1f %% of mdip, the steady field gives\n', ...
            100*rob.m_axial/rob.mdip);
    fprintf('           F_z = m_z dBz/dz = %+.3e N = %+.2f %% of weight\n', ...
            Fz, 100*Fz/(rob.mass*9.81));
    fprintf('           That force is the axial trap, and it is now set independently\n');
    fprintf('           of the rotating drive field. Section 15.2 is the derivation.\n\n');
end
