; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
data_dir = task_sequences

[env]
platform = espressif32@^6.11.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
	-D USE_SYNC=0
	-D SYNC_AS_SERVER=1
	-D SYNC_LATENCY_US=15
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
monitor_filters = esp32_exception_decoder

[env:current_pid]
build_src_filter = +<*> -<main_*.cpp> +<main_current_pid.cpp>
lib_deps =
	${env.lib_deps}
	br3ttb/PID-AutoTune@^1.0.0

[env:serialcomm_demo]
build_src_filter = +<*> -<main_*.cpp> +<main_serialcomm_demo.cpp>

[env:experiment]
build_src_filter = +<*> -<main_*.cpp> +<main_experiment.cpp>
board_build.filesystem = spiffs
lib_deps =
	${env.lib_deps}
	br3ttb/PID-AutoTune@^1.0.0

[env:state_space]
build_src_filter = +<*> -<main_*.cpp> +<main_state_space.cpp>
