#ifndef PMWSETUP_H
#define PMWSETUP_H
// 6-Channel Phase Shift PWM Code from Runtime Micro
// Uses Mega2560 16 bit Timers 1, 3, 4 and 5. 60 degree shifts
// Timer setup code generated by RTM_TimerCalc v1.4

/////////////////////////////////////////////////////////////////////////////
// UN-COMMENT FREQUENCY DESIRED 

//#define TIMER_FREQ_50HZ
//#define TIMER_FREQ_60HZ

#define TIMER_FREQ_300HZ

//#define TIMER_FREQ_500HZ
////////////////////////////////////////////////////////////////////////////

#if defined TIMER_FREQ_50HZ
int const ICAP_NDiv=20000;
int const T5_ICAP=40000-1;
int PRESCALE = 2;
int ADJ_CONST = 10;
int WAIT_CONST = 70;

#elif defined TIMER_FREQ_60HZ
int const ICAP_NDiv=16667;
int const T5_ICAP=33333-1;
int PRESCALE = 2;
int ADJ_CONST = 10;
int WAIT_CONST = 70;

#elif defined TIMER_FREQ_300HZ
int const ICAP_NDiv=26667;
int const T5_ICAP=53333-1;
int PRESCALE = 1;
int ADJ_CONST = 50;
int WAIT_CONST = 20;

#elif defined TIMER_FREQ_500HZ
int const ICAP_NDiv=16000;
int const T5_ICAP=32000-1;
int PRESCALE = 1;
int ADJ_CONST = 25;
int WAIT_CONST = 20;

#endif
#endif // PMWSETUP_H